package dashboard;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.config;

public class FormBarang extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    String sql,kelas;
    ResultSet res;
    Date jdc = new Date();

    /**
     * Creates new form FormBarang
     */
    public FormBarang() throws ClassNotFoundException {
        initComponents();
        
        config k = new config();
        k.config();
        con = k.con;
        stat=k.stm;
        
        setLocationRelativeTo(this);
        load_table();
//        kosong();
        
        
    }
    private void load_table(){
        DefaultTableModel model = (DefaultTableModel) TableBarang.getModel();
        try{
            String sql = "SELECT * FROM tb_barang";
            res=stat.executeQuery(sql);
            while(res.next()){
                
                model.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6)
                });
            }
            TableBarang.setModel(model);
        } catch(Exception e){
            
        }
    }
    
    private void bersih(){
        TeksKodebarang.setText("");
        TeksNamabarang.setText("");
        TeksHargabeli.setText("");
        TeksHargajual.setText("");
        TeksStokbarang.setText("");
    }
    
    private void freshtabel(){
        DefaultTableModel mod = (DefaultTableModel) TableBarang.getModel();
        mod.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Kodebarang = new javax.swing.JLabel();
        Namabarang = new javax.swing.JLabel();
        Jenisbarang = new javax.swing.JLabel();
        Hargabeli = new javax.swing.JLabel();
        Hargajual = new javax.swing.JLabel();
        Stokbarang = new javax.swing.JLabel();
        TeksNamabarang = new javax.swing.JTextField();
        TeksKodebarang = new javax.swing.JTextField();
        TeksHargabeli = new javax.swing.JTextField();
        TeksHargajual = new javax.swing.JTextField();
        TeksStokbarang = new javax.swing.JTextField();
        TombolSimpan = new javax.swing.JButton();
        TombolUpdate = new javax.swing.JButton();
        TombolDelete = new javax.swing.JButton();
        TombolReset = new javax.swing.JButton();
        TeksPencarian = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBarang = new javax.swing.JTable();
        TombolKeluar = new javax.swing.JButton();
        ComboBoxJenisbarang = new javax.swing.JComboBox<>();
        TombolCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel1.setText("Form Data Barang");

        Kodebarang.setText("Kode Barang");

        Namabarang.setText("Nama Barang");

        Jenisbarang.setText("Jenis Barang");

        Hargabeli.setText("Harga Beli");

        Hargajual.setText("Harga Jual");

        Stokbarang.setText("Stok Barang");

        TeksKodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeksKodebarangActionPerformed(evt);
            }
        });

        TombolSimpan.setText("Simpan");
        TombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolSimpanActionPerformed(evt);
            }
        });

        TombolUpdate.setText("Update");
        TombolUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolUpdateActionPerformed(evt);
            }
        });

        TombolDelete.setText("Delete");
        TombolDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolDeleteActionPerformed(evt);
            }
        });

        TombolReset.setText("Reset");
        TombolReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolResetActionPerformed(evt);
            }
        });

        TeksPencarian.setText("Pencarian");

        TableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga Beli", "Harga Jual", "Stok"
            }
        ));
        jScrollPane1.setViewportView(TableBarang);

        TombolKeluar.setText("Keluar");
        TombolKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolKeluarActionPerformed(evt);
            }
        });

        ComboBoxJenisbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman" }));
        ComboBoxJenisbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxJenisbarangActionPerformed(evt);
            }
        });

        TombolCari.setText("Cari");
        TombolCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TombolKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Kodebarang)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Jenisbarang)
                                            .addComponent(Stokbarang)
                                            .addComponent(Hargajual)
                                            .addComponent(Hargabeli))
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Namabarang)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TeksKodebarang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TeksNamabarang, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                    .addComponent(TeksHargabeli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                    .addComponent(TeksHargajual, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TeksStokbarang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboBoxJenisbarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(TombolCari, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TeksPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(TombolSimpan)
                                .addGap(17, 17, 17)
                                .addComponent(TombolUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(TombolDelete)
                                .addGap(18, 18, 18)
                                .addComponent(TombolReset, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(40, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TombolKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Jenisbarang)
                        .addComponent(ComboBoxJenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TeksKodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Kodebarang))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TeksPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TombolCari)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TeksNamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Namabarang)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeksHargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hargabeli))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeksHargajual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hargajual))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeksStokbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stokbarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TombolSimpan)
                    .addComponent(TombolUpdate)
                    .addComponent(TombolDelete)
                    .addComponent(TombolReset))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_TombolKeluarActionPerformed

    private void TombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolSimpanActionPerformed
        if(TeksKodebarang.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Kode Barang !");
        }else if(TeksNamabarang.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Nama Barang !");
        }else if(ComboBoxJenisbarang.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Jenis Barang !");
        }else if(TeksHargabeli.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Harga Beli Barang !");
        }else if(TeksHargajual.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Harga Jual Barang !");
        }else if(TeksStokbarang.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Stok Barang !");
        }else{
            try{
                String sql = "INSERT INTO tb_barang VALUES('"+TeksKodebarang.getText()+"','"+TeksNamabarang.getText()
                                                            +"''"+ComboBoxJenisbarang.getSelectedItem()+"','"+TeksHargabeli.getText()
                                                            +"''"+TeksHargajual.getText()+"','"+TeksStokbarang.getText()+"')";
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "Simpan Data Berhasil!");
                
                bersih();
                freshtabel();
                load_table();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Simpan Data Gagal! "+e.getMessage());
            }
        }
    }//GEN-LAST:event_TombolSimpanActionPerformed

    private void TeksKodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeksKodebarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeksKodebarangActionPerformed

    private void ComboBoxJenisbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxJenisbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxJenisbarangActionPerformed

    private void TombolUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolUpdateActionPerformed
        if(TeksKodebarang.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Kode Barang !");
            TeksKodebarang.requestFocus();
        }else if(TeksNamabarang.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Nama Barang !");
            TeksNamabarang.requestFocus();
        }else if(ComboBoxJenisbarang.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Jenis Barang !");
            ComboBoxJenisbarang.requestFocus();
        }else if(TeksHargabeli.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Harga Beli Barang !");
            ComboBoxJenisbarang.requestFocus();
        }else if(TeksHargajual.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Harga Jual Barang !");
            TeksHargajual.requestFocus();
        }else if(TeksStokbarang.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Stok Barang !");
            TeksStokbarang.requestFocus();
        }else{
            try{
                String sql = "UPDATE tb_barang SET nama_barang='"+TeksNamabarang.getText()+"',jenis_barang='"+ComboBoxJenisbarang.getSelectedItem()
                                                            +"',harga_barang='"+TeksHargabeli.getText()+"',harga_jual='"+TeksHargajual.getText()
                                                            +"',stok='"+TeksStokbarang.getText()+"' WHERE kd_barang = '"+TeksKodebarang.getText()+"'";
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "Update Data Berhasil!");
                
                bersih();
                freshtabel();
                load_table();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Update Data Gagal! "+e.getMessage());
            }
        }
    }//GEN-LAST:event_TombolUpdateActionPerformed

    private void TombolDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolDeleteActionPerformed
        if(TeksKodebarang.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Kode Barang yang akan DIHAPUS!");
            TeksKodebarang.requestFocus();
        }else{
        try{
                String sql = "DELETE FROM tb_barang WHERE kd_barang = '"+TeksKodebarang.getText()+"'";
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "Hapus Data Berhasil!");
                
                bersih();
                freshtabel();
                load_table();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Hapus Data Gagal! "+e.getMessage());
            }
        }
    }//GEN-LAST:event_TombolDeleteActionPerformed

    private void TombolResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolResetActionPerformed
        bersih();
    }//GEN-LAST:event_TombolResetActionPerformed

    private void TombolCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolCariActionPerformed
        DefaultTableModel model = (DefaultTableModel) TableBarang.getModel();
        if(TeksPencarian.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Isi Kolom Pencarian");
            TeksPencarian.requestFocus();
        }else{
            try{
                String sql = "SELECT * FROM tb_barang WHERE kd_barang LIKE '%"+TeksPencarian.getText()+
                             "%' OR nama_barang LIKE '%"+TeksPencarian.getText()+"%'";
                freshtabel();
                res=stat.executeQuery(sql);
                while(res.next()){

                    model.addRow(new Object[]{
                        res.getString(1),
                        res.getString(2),
                        res.getString(3),
                        res.getString(4),
                        res.getString(5),
                        res.getString(6)
                    });
                }
                
                TableBarang.setModel(model);

            } catch(Exception e){

            }
        }
    }//GEN-LAST:event_TombolCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormBarang().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FormBarang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxJenisbarang;
    private javax.swing.JLabel Hargabeli;
    private javax.swing.JLabel Hargajual;
    private javax.swing.JLabel Jenisbarang;
    private javax.swing.JLabel Kodebarang;
    private javax.swing.JLabel Namabarang;
    private javax.swing.JLabel Stokbarang;
    private javax.swing.JTable TableBarang;
    private javax.swing.JTextField TeksHargabeli;
    private javax.swing.JTextField TeksHargajual;
    private javax.swing.JTextField TeksKodebarang;
    private javax.swing.JTextField TeksNamabarang;
    private javax.swing.JTextField TeksPencarian;
    private javax.swing.JTextField TeksStokbarang;
    private javax.swing.JButton TombolCari;
    private javax.swing.JButton TombolDelete;
    private javax.swing.JButton TombolKeluar;
    private javax.swing.JButton TombolReset;
    private javax.swing.JButton TombolSimpan;
    private javax.swing.JButton TombolUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
