package dashboard;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.config;
import javax.swing.JOptionPane;

public class FormPengguna extends javax.swing.JFrame {
    
    Connection con;
    Statement stat;
    String sql,kelas;
    ResultSet res;
    Date jdc = new Date();
    
    /** Creates new form FormPengguna */
    public FormPengguna() throws ClassNotFoundException {
        initComponents();
        config k = new config();
        k.config();
        con = k.con;
        stat=k.stm;
        
        setLocationRelativeTo(this);
        load_table();
    }
    private void load_table(){
        DefaultTableModel model = (DefaultTableModel) TablePengguna.getModel();
        try{
            String sql = "SELECT * FROM tb_pengguna";
            res=stat.executeQuery(sql);
            while(res.next()){
                
                model.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(5),
                    res.getString(6),
                    res.getString(7)
                });
            }
            TablePengguna.setModel(model);
        } catch(Exception e){
            
        }
    }
    private void bersih(){
        TeksKodepengguna.setText("");
        TeksNamapengguna.setText("");
        TeksNomorHP.setText("");
        TeksUsername.setText("");
        TeksPassword.setText("");
    }
    
    private void freshtabel(){
        DefaultTableModel mod = (DefaultTableModel) TablePengguna.getModel();
        mod.setRowCount(0);
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TombolSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePengguna = new javax.swing.JTable();
        TombolUpdate = new javax.swing.JButton();
        TombolDelete = new javax.swing.JButton();
        TombolReset = new javax.swing.JButton();
        Formpengguna = new javax.swing.JLabel();
        TeksKodepengguna = new javax.swing.JTextField();
        Kodepengguna = new javax.swing.JLabel();
        Namapengguna = new javax.swing.JLabel();
        Jenisbarang = new javax.swing.JLabel();
        TombolKeluar = new javax.swing.JButton();
        NomorHP = new javax.swing.JLabel();
        TeksNomorHP = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        TeksUsername = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        TeksPassword = new javax.swing.JTextField();
        TeksNamapengguna = new javax.swing.JTextField();
        RadioButtonPria = new javax.swing.JRadioButton();
        RadioButtonWanita = new javax.swing.JRadioButton();
        Jabatan = new javax.swing.JLabel();
        ComboBoxjabatan = new javax.swing.JComboBox<>();
        TeksPencarian = new javax.swing.JTextField();
        TombolCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TombolSimpan.setText("Simpan");
        TombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolSimpanActionPerformed(evt);
            }
        });

        TablePengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Pengguna", "Nama Pengguna", "Jabatan", "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(TablePengguna);

        TombolUpdate.setText("Update");
        TombolUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolUpdateActionPerformed(evt);
            }
        });

        TombolDelete.setText("Delete");
        TombolDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolDeleteActionPerformed(evt);
            }
        });

        TombolReset.setText("Reset");
        TombolReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolResetActionPerformed(evt);
            }
        });

        Formpengguna.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        Formpengguna.setText("Form Pengguna");

        Kodepengguna.setText("Kode Pengguna");

        Namapengguna.setText("Nama Pengguna");

        Jenisbarang.setText("Jenis Kelamin");

        TombolKeluar.setText("Keluar");
        TombolKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolKeluarActionPerformed(evt);
            }
        });

        NomorHP.setText("Nomor HP");

        TeksNomorHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeksNomorHPActionPerformed(evt);
            }
        });

        Username.setText("Username");

        TeksUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeksUsernameActionPerformed(evt);
            }
        });

        Password.setText("Password");

        buttonGroup1.add(RadioButtonPria);
        RadioButtonPria.setText("Pria");
        RadioButtonPria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonPriaActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioButtonWanita);
        RadioButtonWanita.setText("Wanita");
        RadioButtonWanita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonWanitaActionPerformed(evt);
            }
        });

        Jabatan.setText("Jabatan");

        ComboBoxjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "manager", "admin", "kasir" }));
        ComboBoxjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxjabatanActionPerformed(evt);
            }
        });

        TeksPencarian.setText("Pencarian");

        TombolCari.setText("Cari");
        TombolCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TombolSimpan)
                        .addGap(17, 17, 17)
                        .addComponent(TombolUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(TombolDelete)
                        .addGap(18, 18, 18)
                        .addComponent(TombolReset, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Formpengguna)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TombolKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Namapengguna)
                                            .addComponent(Kodepengguna))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TeksKodepengguna, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TeksNamapengguna, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Jenisbarang)
                                        .addGap(51, 51, 51)
                                        .addComponent(RadioButtonPria)
                                        .addGap(59, 59, 59)
                                        .addComponent(RadioButtonWanita))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NomorHP)
                                            .addComponent(Username)
                                            .addComponent(Password)
                                            .addComponent(Jabatan))
                                        .addGap(78, 78, 78)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ComboBoxjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(TeksUsername)
                                                .addComponent(TeksNomorHP)
                                                .addComponent(TeksPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TombolCari, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TeksPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Formpengguna)
                    .addComponent(TombolKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TeksPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TombolCari))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TeksKodepengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Kodepengguna)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TeksNamapengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Namapengguna))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jenisbarang)
                            .addComponent(RadioButtonPria)
                            .addComponent(RadioButtonWanita))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jabatan)
                            .addComponent(ComboBoxjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeksNomorHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomorHP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeksUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeksPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TombolSimpan)
                    .addComponent(TombolUpdate)
                    .addComponent(TombolDelete)
                    .addComponent(TombolReset))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_TombolKeluarActionPerformed

    private void TombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolSimpanActionPerformed
        if(TeksKodepengguna.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Kode Pengguna !");
        }else if(TeksNamapengguna.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Nama Pengguna !");
        }else if(!RadioButtonPria.isSelected() && !RadioButtonWanita.isSelected()){
            JOptionPane.showMessageDialog(null, "Lengkapi Jenis Kelamin !");
        }else if(ComboBoxjabatan.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Jabatan !");
        }else if(TeksNomorHP.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Nomor HP !");
        }else if(TeksUsername.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Username !");
        }else if(TeksPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Password !");
        }else{
            try{
                String jk = "";
                if(RadioButtonPria.isSelected()){
                    jk = RadioButtonPria.getText();
                } else if (RadioButtonWanita.isSelected()){
                    jk = RadioButtonWanita.getText();
                }
                
                String sql = "INSERT INTO tb_pengguna VALUES('"+TeksKodepengguna.getText()+"','"+TeksNamapengguna.getText()
                                                            +"','"+jk+"','"+TeksNomorHP.getText()+"','"+ComboBoxjabatan.getSelectedItem()
                                                            +"','"+TeksUsername.getText()+"','"+TeksPassword.getText()
                                                            +"')";
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "Simpan Data Berhasil!");
                
                bersih();
                freshtabel();
                load_table();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Simpan Data Gagal! "+e.getMessage());
            }
        }
    }//GEN-LAST:event_TombolSimpanActionPerformed

    private void RadioButtonWanitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonWanitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonWanitaActionPerformed

    private void ComboBoxjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxjabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxjabatanActionPerformed

    private void TeksNomorHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeksNomorHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeksNomorHPActionPerformed

    private void TombolUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolUpdateActionPerformed
        if(TeksKodepengguna.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Kode Pengguna !");
        }else if(TeksNamapengguna.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Nama Pengguna !");
        }else if(!RadioButtonPria.isSelected() && !RadioButtonWanita.isSelected()){
            JOptionPane.showMessageDialog(null, "Lengkapi Jenis Kelamin !");
        }else if(ComboBoxjabatan.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Jabatan !");
        }else if(TeksNomorHP.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Nomor HP !");
        }else if(TeksUsername.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Username !");
        }else if(TeksPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Password !");
        }else{
            try{
                String jk = "";
                if(RadioButtonPria.isSelected()){
                    jk = RadioButtonPria.getText();
                } else if (RadioButtonWanita.isSelected()){
                    jk = RadioButtonWanita.getText();
                }
                
                String sql = "UPDATE tb_pengguna SET nama_pengguna='"+TeksNamapengguna.getText()+"',jabatan='"+ComboBoxjabatan.getSelectedItem()
                                                            +"',jk='"+jk+"',nohp='"+TeksNomorHP.getText()
                                                            +"',jabatan='"+ComboBoxjabatan.getSelectedItem()
                                                            +"',username='"+TeksUsername.getText()+"',password='"+TeksPassword.getText()
                                                            +"' WHERE kd_pengguna = '"+TeksKodepengguna.getText()+"'";
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "Simpan Data Berhasil!");
                
                bersih();
                freshtabel();
                load_table();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Simpan Data Gagal! "+e.getMessage());
            }
        }
    }//GEN-LAST:event_TombolUpdateActionPerformed

    private void TombolDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolDeleteActionPerformed
        if(TeksKodepengguna.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Kode Pengguna yang akan DIHAPUS!");
            TeksKodepengguna.requestFocus();
        }else{
        try{
                String sql = "DELETE FROM tb_pengguna WHERE kd_pengguna = '"+TeksKodepengguna.getText()+"'";
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "Hapus Data Berhasil!");
                
                bersih();
                freshtabel();
                load_table();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Hapus Data Gagal! "+e.getMessage());
            }
        }
    }//GEN-LAST:event_TombolDeleteActionPerformed

    private void TombolResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolResetActionPerformed
        bersih();
    }//GEN-LAST:event_TombolResetActionPerformed

    private void TombolCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolCariActionPerformed
        DefaultTableModel model = (DefaultTableModel) TablePengguna.getModel();
        if(TeksPencarian.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Isi Kolom Pencarian");
            TeksPencarian.requestFocus();
        }else{
            try{
                String sql = "SELECT * FROM tb_pengguna WHERE kd_pengguna LIKE '%"+TeksPencarian.getText()+
                "%' OR nama_pengguna LIKE '%"+TeksPencarian.getText()+"%'";
                freshtabel();
                res=stat.executeQuery(sql);
                while(res.next()){

                    model.addRow(new Object[]{
                        res.getString(1),
                        res.getString(2),
                        res.getString(5),
                        res.getString(6),
                        res.getString(7)
                    });
                }

                TablePengguna.setModel(model);

            } catch(Exception e){

            }
        }
    }//GEN-LAST:event_TombolCariActionPerformed

    private void TeksUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeksUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeksUsernameActionPerformed

    private void RadioButtonPriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonPriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonPriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormPengguna().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FormPengguna.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxjabatan;
    private javax.swing.JLabel Formpengguna;
    private javax.swing.JLabel Jabatan;
    private javax.swing.JLabel Jenisbarang;
    private javax.swing.JLabel Kodepengguna;
    private javax.swing.JLabel Namapengguna;
    private javax.swing.JLabel NomorHP;
    private javax.swing.JLabel Password;
    private javax.swing.JRadioButton RadioButtonPria;
    private javax.swing.JRadioButton RadioButtonWanita;
    private javax.swing.JTable TablePengguna;
    private javax.swing.JTextField TeksKodepengguna;
    private javax.swing.JTextField TeksNamapengguna;
    private javax.swing.JTextField TeksNomorHP;
    private javax.swing.JTextField TeksPassword;
    private javax.swing.JTextField TeksPencarian;
    private javax.swing.JTextField TeksUsername;
    private javax.swing.JButton TombolCari;
    private javax.swing.JButton TombolDelete;
    private javax.swing.JButton TombolKeluar;
    private javax.swing.JButton TombolReset;
    private javax.swing.JButton TombolSimpan;
    private javax.swing.JButton TombolUpdate;
    private javax.swing.JLabel Username;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
