package dashboard;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.config;

public class FormPasok extends javax.swing.JFrame {

    Connection con;
    Statement stat;
    String sql,kelas;
    ResultSet res;
    Date jdc = new Date();
    
    /**
     * Creates new form FormPasok
     */
    public FormPasok() throws ClassNotFoundException {
        initComponents();
        
        config k = new config();
        k.config();
        con = k.con;
        stat=k.stm;
        
        setLocationRelativeTo(this);
        load_table();
    }
    private void load_table(){
        DefaultTableModel model = (DefaultTableModel) TablePasokan.getModel();
        try{
            String sql = "SELECT * FROM tb_pasok";
            res=stat.executeQuery(sql);
            while(res.next()){
                
                model.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6)
                });
            }
            TablePasokan.setModel(model);
        } catch(Exception e){
            
        }
    }
    
    private void bersih(){
        TeksKodebarang.setText("");
        TeksNamabarang.setText("");
        TeksKodepasok.setText("");
        TeksJumlah.setText("");
        TeksPemasok.setText("");
    }
    
    private void freshtabel(){
        DefaultTableModel mod = (DefaultTableModel) TablePasokan.getModel();
        mod.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TeksNamabarang = new javax.swing.JTextField();
        TeksJumlah = new javax.swing.JTextField();
        TeksPemasok = new javax.swing.JTextField();
        TombolSimpan = new javax.swing.JButton();
        TombolUpdate = new javax.swing.JButton();
        TombolDelete = new javax.swing.JButton();
        Formpasokan = new javax.swing.JLabel();
        Kodepasok = new javax.swing.JLabel();
        Kodebarang = new javax.swing.JLabel();
        Jenisbarang = new javax.swing.JLabel();
        Jumlah = new javax.swing.JLabel();
        Tanggalmasuk = new javax.swing.JLabel();
        Pemasok = new javax.swing.JLabel();
        TeksKodebarang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePasokan = new javax.swing.JTable();
        TombolReset = new javax.swing.JButton();
        TeksKodepasok = new javax.swing.JTextField();
        TombolKeluar = new javax.swing.JButton();
        TeksPencarian = new javax.swing.JTextField();
        TombolCari = new javax.swing.JButton();
        KalenderTanggalMasuk = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TombolSimpan.setText("Simpan");
        TombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolSimpanActionPerformed(evt);
            }
        });

        TombolUpdate.setText("Update");
        TombolUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolUpdateActionPerformed(evt);
            }
        });

        TombolDelete.setText("Delete");
        TombolDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolDeleteActionPerformed(evt);
            }
        });

        Formpasokan.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        Formpasokan.setText("Form Pasokan");

        Kodepasok.setText("Kode Pasok");

        Kodebarang.setText("Kode barang");

        Jenisbarang.setText("Nama Barang");

        Jumlah.setText("Jumlah");

        Tanggalmasuk.setText("Tanggal Masuk");

        Pemasok.setText("Pemasok");

        TablePasokan.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        TablePasokan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Pasok", "Kode Barang", "Nama Barang", "Jumlah", "Tanggal Masuk", "Pemasok"
            }
        ));
        jScrollPane1.setViewportView(TablePasokan);

        TombolReset.setText("Reset");
        TombolReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolResetActionPerformed(evt);
            }
        });

        TombolKeluar.setText("Keluar");
        TombolKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolKeluarActionPerformed(evt);
            }
        });

        TeksPencarian.setText("Pencarian");
        TeksPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeksPencarianActionPerformed(evt);
            }
        });

        TombolCari.setText("Cari");
        TombolCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Formpasokan)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jenisbarang)
                            .addComponent(Tanggalmasuk)
                            .addComponent(Jumlah)
                            .addComponent(Kodebarang)
                            .addComponent(Kodepasok)
                            .addComponent(Pemasok))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TeksPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(TombolKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TeksKodepasok, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TeksKodebarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TeksJumlah, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TeksNamabarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TombolCari, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(TeksPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(212, 212, 212)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(KalenderTanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TombolSimpan)
                .addGap(17, 17, 17)
                .addComponent(TombolUpdate)
                .addGap(18, 18, 18)
                .addComponent(TombolDelete)
                .addGap(18, 18, 18)
                .addComponent(TombolReset, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Formpasokan)
                    .addComponent(TombolKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TeksNamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jenisbarang))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TeksJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jumlah))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TeksPencarian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TeksKodepasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Kodepasok)
                                .addComponent(TombolCari)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TeksKodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Kodebarang)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tanggalmasuk)
                        .addGap(212, 212, 212))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(KalenderTanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pemasok)
                    .addComponent(TeksPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TombolSimpan)
                    .addComponent(TombolUpdate)
                    .addComponent(TombolDelete)
                    .addComponent(TombolReset))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_TombolKeluarActionPerformed

    private void TombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolSimpanActionPerformed
        if(TeksKodepasok.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Kode Pasok !");
        }else if(TeksKodebarang.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Kode Barang !");
        }else if(TeksNamabarang.getText().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Nama Barang !");
        }else if(TeksJumlah.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Jumlah Barang !");
        }else if(TeksPemasok.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Pemasok Barang !");
        }else{
            
            try{
                String sql = "INSERT INTO tb_pasok VALUES('"+TeksKodepasok.getText()+"','"+TeksKodebarang.getText()
                                                            +"','"+TeksNamabarang.getText()+"','"+TeksJumlah.getText()
                                                            +"','"+KalenderTanggalMasuk.getDate()+"','"+TeksPemasok.getText()+"')";
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "Simpan Data Berhasil!");
                
                bersih();
                freshtabel();
                load_table();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Simpan Data Gagal! "+e.getMessage());
            }
        }
    }//GEN-LAST:event_TombolSimpanActionPerformed

    private void TombolDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolDeleteActionPerformed
        if(TeksKodepasok.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Kode Pasok yang akan DIHAPUS!");
            TeksKodepasok.requestFocus();
        }else{
        try{
                String sql = "DELETE FROM tb_pasok WHERE kd_pasok = '"+TeksKodepasok.getText()+"'";
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "Hapus Data Berhasil!");
                
                bersih();
                freshtabel();
                load_table();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Hapus Data Gagal! "+e.getMessage());
            }
        }
    }//GEN-LAST:event_TombolDeleteActionPerformed

    private void TombolCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolCariActionPerformed
        DefaultTableModel model = (DefaultTableModel) TablePasokan.getModel();
        if(TeksPencarian.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Isi Kolom Pencarian");
            TeksPencarian.requestFocus();
        }else{
            try{
                String sql = "SELECT * FROM tb_pasok WHERE kd_pasok LIKE '%"+TeksPencarian.getText()+
                "%' OR nama_barang LIKE '%"+TeksPencarian.getText()+"'OR kd_barang LIKE '%"+TeksPencarian.getText()+"%'";
                freshtabel();
                res=stat.executeQuery(sql);
                while(res.next()){

                    model.addRow(new Object[]{
                        res.getString(1),
                        res.getString(2),
                        res.getString(3),
                        res.getString(4),
                        res.getString(5),
                        res.getString(6)
                    });
                }

                TablePasokan.setModel(model);

            } catch(Exception e){

            }
        }
    }//GEN-LAST:event_TombolCariActionPerformed

    private void TeksPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeksPencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeksPencarianActionPerformed

    private void TombolUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolUpdateActionPerformed
        if(TeksKodepasok.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Kode Pasok !");
        }else if(TeksKodebarang.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Kode Barang !");
        }else if(TeksNamabarang.getText().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Nama Barang !");
        }else if(TeksJumlah.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Jumlah Barang !");
        }else if(TeksPemasok.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Pemasok Barang !");
        }else{
            
            try{
                String sql = "UPDATE tb_pasok SET kd_barang='"+TeksKodebarang.getText()
                                                            +"',nama_barang='"+TeksNamabarang.getText()+"',jumlah='"+TeksJumlah.getText()
                                                            +"',tanggal='"+ KalenderTanggalMasuk.getDate()+"',pemasok='"+TeksPemasok.getText()+"' WHERE kd_pasok='"+TeksKodepasok.getText()+"'";
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "Simpan Data Berhasil!");
                
                bersih();
                freshtabel();
                load_table();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Simpan Data Gagal! "+e.getMessage());
            }
        }
    }//GEN-LAST:event_TombolUpdateActionPerformed

    private void TombolResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolResetActionPerformed
        bersih();
    }//GEN-LAST:event_TombolResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormPasok().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FormPasok.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Formpasokan;
    private javax.swing.JLabel Jenisbarang;
    private javax.swing.JLabel Jumlah;
    private com.toedter.calendar.JCalendar KalenderTanggalMasuk;
    private javax.swing.JLabel Kodebarang;
    private javax.swing.JLabel Kodepasok;
    private javax.swing.JLabel Pemasok;
    private javax.swing.JTable TablePasokan;
    private javax.swing.JLabel Tanggalmasuk;
    private javax.swing.JTextField TeksJumlah;
    private javax.swing.JTextField TeksKodebarang;
    private javax.swing.JTextField TeksKodepasok;
    private javax.swing.JTextField TeksNamabarang;
    private javax.swing.JTextField TeksPemasok;
    private javax.swing.JTextField TeksPencarian;
    private javax.swing.JButton TombolCari;
    private javax.swing.JButton TombolDelete;
    private javax.swing.JButton TombolKeluar;
    private javax.swing.JButton TombolReset;
    private javax.swing.JButton TombolSimpan;
    private javax.swing.JButton TombolUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
