
package dashboard;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.config;

public class FormPemasok extends javax.swing.JFrame {
    
    Connection con;
    Statement stat;
    String sql,kelas;
    ResultSet res;
    Date jdc = new Date();

    /**
     * Creates new form FormPemasok
     */
    public FormPemasok() throws ClassNotFoundException {
        initComponents();
        config k = new config();
        k.config();
        con = k.con;
        stat=k.stm;
        
        setLocationRelativeTo(this);
        load_table();
    }
    
    private void load_table(){
        DefaultTableModel model = (DefaultTableModel) TablePemasok.getModel();
        try{
            String sql = "SELECT * FROM tb_pemasok";
            res=stat.executeQuery(sql);
            while(res.next()){
                
                model.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4)
                });
            }
            TablePemasok.setModel(model);
        } catch(Exception e){
            
        }
    }
    
    private void bersih(){
        TeksKodepemasok.setText("");
        TeksNamapemasok.setText("");
        TextAreaAlamat.setText("");
        TeksNomorHP.setText("");
    }
    
    private void freshtabel(){
        DefaultTableModel mod = (DefaultTableModel) TablePemasok.getModel();
        mod.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kodepemasok = new javax.swing.JLabel();
        TombolSimpan = new javax.swing.JButton();
        Namapemasok = new javax.swing.JLabel();
        TombolUpdate = new javax.swing.JButton();
        TombolDelete = new javax.swing.JButton();
        TombolReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePemasok = new javax.swing.JTable();
        Alamat = new javax.swing.JLabel();
        TombolKeluar = new javax.swing.JButton();
        NomorHP = new javax.swing.JLabel();
        TeksNamapemasok = new javax.swing.JTextField();
        TeksKodepemasok = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TeksNomorHP = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaAlamat = new javax.swing.JTextArea();
        TeksPencarian = new javax.swing.JTextField();
        TombolCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Kodepemasok.setText("Kode Pemasok");

        TombolSimpan.setText("Simpan");
        TombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolSimpanActionPerformed(evt);
            }
        });

        Namapemasok.setText("Nama Pemasok");

        TombolUpdate.setText("Update");
        TombolUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolUpdateActionPerformed(evt);
            }
        });

        TombolDelete.setText("Delete");
        TombolDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolDeleteActionPerformed(evt);
            }
        });

        TombolReset.setText("Reset");
        TombolReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolResetActionPerformed(evt);
            }
        });

        TablePemasok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Pemasok", "Nama Pemasok", "Alamat", "Pemasok"
            }
        ));
        jScrollPane1.setViewportView(TablePemasok);

        Alamat.setText("Alamat");

        TombolKeluar.setText("Keluar");
        TombolKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolKeluarActionPerformed(evt);
            }
        });

        NomorHP.setText("Nomor HP");

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel1.setText("Form Pemasok");

        TextAreaAlamat.setColumns(20);
        TextAreaAlamat.setRows(5);
        jScrollPane2.setViewportView(TextAreaAlamat);

        TeksPencarian.setText("Pencarian");

        TombolCari.setText("Cari");
        TombolCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TombolKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Namapemasok, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Alamat))
                                        .addComponent(NomorHP))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(TeksKodepemasok, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TeksNamapemasok, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(TeksNomorHP)))
                                .addComponent(Kodepemasok))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TombolCari, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TeksPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(TombolSimpan)
                        .addGap(17, 17, 17)
                        .addComponent(TombolUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(TombolDelete)
                        .addGap(18, 18, 18)
                        .addComponent(TombolReset, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TombolKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeksKodepemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kodepemasok)
                    .addComponent(TombolCari)
                    .addComponent(TeksPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TeksNamapemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Namapemasok))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Alamat)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeksNomorHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomorHP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TombolSimpan)
                    .addComponent(TombolUpdate)
                    .addComponent(TombolDelete)
                    .addComponent(TombolReset))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_TombolKeluarActionPerformed

    private void TombolCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolCariActionPerformed
        DefaultTableModel model = (DefaultTableModel) TablePemasok.getModel();
        if(TeksPencarian.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Isi Kolom Pencarian");
            TeksPencarian.requestFocus();
        }else{
            try{
                String sql = "SELECT * FROM tb_pemasok WHERE kd_pemasok LIKE '%"+TeksPencarian.getText()+
                "%' OR nama_pemasok LIKE '%"+TeksPencarian.getText()+"%'";
                freshtabel();
                res=stat.executeQuery(sql);
                while(res.next()){

                    model.addRow(new Object[]{
                        res.getString(1),
                        res.getString(2),
                        res.getString(3),
                        res.getString(4)
                    });
                }

                TablePemasok.setModel(model);

            } catch(Exception e){

            }
        }
    }//GEN-LAST:event_TombolCariActionPerformed

    private void TombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolSimpanActionPerformed
        if(TeksKodepemasok.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Kode Pemasok !");
        }else if(TeksNamapemasok.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Nama Pemasok !");
        }else if(TextAreaAlamat.getText().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Alamat !");
        }else if(TeksNomorHP.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Nomor HP !");
        }else{
            try{
                String sql = "INSERT INTO tb_pemasok VALUES('"+TeksKodepemasok.getText()+"','"+TeksNamapemasok.getText()
                                                            +"','"+TextAreaAlamat.getText()+"','"+TeksNomorHP.getText()+"')";
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "Simpan Data Berhasil!");
                
                bersih();
                freshtabel();
                load_table();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Simpan Data Gagal! "+e.getMessage());
            }
        }
    }//GEN-LAST:event_TombolSimpanActionPerformed

    private void TombolDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolDeleteActionPerformed
        if(TeksKodepemasok.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Kode Pemasok yang akan DIHAPUS!");
            TeksKodepemasok.requestFocus();
        }else{
        try{
                String sql = "DELETE FROM tb_pemasok WHERE kd_pemasok = '"+TeksKodepemasok.getText()+"'";
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "Hapus Data Berhasil!");
                
                bersih();
                freshtabel();
                load_table();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Hapus Data Gagal! "+e.getMessage());
            }
        }
    }//GEN-LAST:event_TombolDeleteActionPerformed

    private void TombolUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolUpdateActionPerformed
        if(TeksKodepemasok.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Kode Pemasok !");
        }else if(TeksNamapemasok.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Nama Pemasok !");
        }else if(TextAreaAlamat.getText().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Alamat !");
        }else if(TeksNomorHP.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Nomor HP !");
        }else{
            try{
                String sql = "UPDATE tb_pemasok SET nama_pemasok='"+TeksNamapemasok.getText()
                                                            +"',alamat='"+TextAreaAlamat.getText()+"',nohp='"+TeksNomorHP.getText()
                                                            +"' WHERE kd_pemasok = '"+TeksKodepemasok.getText()+"'";
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "Update Data Berhasil!");
                
                bersih();
                freshtabel();
                load_table();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Update Data Gagal! "+e.getMessage());
            }
        }
    }//GEN-LAST:event_TombolUpdateActionPerformed

    private void TombolResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolResetActionPerformed
        bersih();
    }//GEN-LAST:event_TombolResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormPemasok().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FormPemasok.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Kodepemasok;
    private javax.swing.JLabel Namapemasok;
    private javax.swing.JLabel NomorHP;
    private javax.swing.JTable TablePemasok;
    private javax.swing.JTextField TeksKodepemasok;
    private javax.swing.JTextField TeksNamapemasok;
    private javax.swing.JTextField TeksNomorHP;
    private javax.swing.JTextField TeksPencarian;
    private javax.swing.JTextArea TextAreaAlamat;
    private javax.swing.JButton TombolCari;
    private javax.swing.JButton TombolDelete;
    private javax.swing.JButton TombolKeluar;
    private javax.swing.JButton TombolReset;
    private javax.swing.JButton TombolSimpan;
    private javax.swing.JButton TombolUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
